### ISSUE TITLE
Pagination should reflect the total number of items returned from server

### ISSUE THREAD

**Issue by dong77** [Loopring/looper#68]

**Comment by dyfvicture** [comment]
server 返回的分页数据结构为:
{
"data":[], //页面展示数据
"pageIndex" : 1, //当前页
"pageSize" : 10, //每页显示条数
"total" : 12 //总记录数
}
#/history/rings 添加了mock数据可以看到total为12分2页显示，因为是同一份mock数据请求第二页时也会转到第一页(pageIndex=1)。其他页面mock数据都展示一页
